foreground            #e2e2e9
background            #121318
selection_foreground  #162e60
selection_background  #b1c6ff
url_color             #b1c6ff
cursor                #b1c6ff

# Black
color0 #121318
color8 #38393f

# Cores principais mapeadas do Wallpaper
color4 #b1c6ff
color12 #b1c6ff
color5 #e0bbdd
color13 #e0bbdd