# Kitty Configuration

# Fontes
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        10

# Janela e Transparência
background_opacity         0.60
dynamic_background_opacity yes
window_padding_width       16
confirm_os_window_close    0

# Cursor
cursor_shape               beam
cursor_blink_interval      0.5

# Cores (Azul Profundo / Deep Navy)
foreground                 #cad3f5
background                 #0d0f18
selection_foreground       #0d0f18
selection_background       #f4dbd6


# Black
color0 #494d64
color8 #5b6078

# Red
color1 #ed8796
color9 #ed8796

# Green
color2  #a6da95
color10 #a6da95

# Yellow
color3  #eed49f
color11 #eed49f

# Blue
color4  #8aadf4
color12 #8aadf4

# Magenta
color5  #f5bde6
color13 #f5bde6

# Cyan
color6  #8bd5ca
color14 #8bd5ca

# White
color7  #b8c0e0
color15 #a5adcb

# Barra de abas
tab_bar_style              powerline
active_tab_foreground      #181926
active_tab_background      #c6a0f6
inactive_tab_foreground    #cad3f5
inactive_tab_background    #1e2030

# Shell
shell zsh
